# ----------------------------------
# Project Metadata
# ----------------------------------
project_name: "Predictive_Maintenance_v1"
author: "Lavanya_Diviti"

# ----------------------------------
# Data Paths
# ----------------------------------
data:
  raw_path: "data/raw/v1_raw.csv"
  processed_dir: "data/processed/"
  current_version: "v1.csv"

# ----------------------------------
# Hyperparameters
# ----------------------------------
model_params:
  algorithm: "RandomForest"
  n_estimators: 100
  max_depth: null
  random_state: 42
  test_size: 0.2

# ----------------------------------
# Deployment Settings
# ----------------------------------
deployment:
  model_path: "models/model.pkl"
  encoder_path: "models/encoder.pkl"
  feature_names_path: "models/feature_names.pkl"
  metadata_path: "models/metadata.json"
  port: 8000
  threshold: 0.5
